version: '3.8'

services:
  postgres:
    container_name: libadmin_database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
  libadmin_service:
    build: .
    ports: 
    - "8080:8080"
    links: 
    - "postgres:postgres"
    depends_on: 
    - postgres
  
volumes:
  postgres: