version: '3.8'

services:
  postgres:
    container_name: libadmin_database
    image: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /mypostgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  libadmin_service:
    container_name: libadmin_service
    image: libadmin
    ports: 
    - "80:80"
    links: 
    - "postgres:postgres"
    depends_on: 
    - postgres
  
volumes:
  postgres: