version: '3.3'

services:
  postgres:
    container_name: libadmin_database
    build: ./database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  libadmin_service:
    container_name: libadmin_service
    build: ./springBootService/
    ports: 
    - "8080:8080"
    links: 
    - "postgres:postgres"
    depends_on: 
    - postgres
  
volumes:
  postgres: