version: '3.8'

services:
  libadmin:
    build: .
    ports: 
    - "8080:8080"
    links: 
    - "postgres:postgres"
    depends_on: 
    - postgres
  postgres:
    container_name: libadmin_database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
volumes:
  postgres: