# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - LibAdmin

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    # Maven install
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    # Docker build
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f13827fd27c498199e395f363e346bc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1d303e3bbc7b4c3595e033738cfb3386 }}

    - name: Build container image to registry
    - run: docker-compose up --build index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f13827fd27c498199e395f363e346bc }}/libadmin:${{ github.sha }}
    - name: Push container image to registry
    - run: docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f13827fd27c498199e395f363e346bc }}/libadmin:${{ github.sha }}  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LibAdmin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2c06cc404c17455ebb6804d77ca47a37 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4f13827fd27c498199e395f363e346bc }}/libadmin:${{ github.sha }}'
