# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - LibAdmin

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: sacregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build ./springBootService -t sacregistry.azurecr.io/libadmin:${{ github.sha }}
          docker push sacregistry.azurecr.io/libadmin:${{ github.sha }}
      - run : |
          docker build ./database -t sacregistry.azurecr.io/MyPostgres:${{ github.sha }}
          docker push sacregistry.azurecr.io/MyPostgres:${{ github.sha }}